// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace STRIPES.Services.Endpoints.V2.ATCPositions.All
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetMapTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "regionMap")]
        #pragma warning disable CS1591
        RegionMap,
        #pragma warning restore CS1591
        [EnumMember(Value = "regionMapPolygon")]
        #pragma warning disable CS1591
        RegionMapPolygon,
        #pragma warning restore CS1591
    }
}
