// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace STRIPES.Services.Endpoints.V2.Positions.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetPositionTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CTR")]
        #pragma warning disable CS1591
        CTR,
        #pragma warning restore CS1591
        [EnumMember(Value = "APP")]
        #pragma warning disable CS1591
        APP,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEP")]
        #pragma warning disable CS1591
        DEP,
        #pragma warning restore CS1591
        [EnumMember(Value = "TWR")]
        #pragma warning disable CS1591
        TWR,
        #pragma warning restore CS1591
        [EnumMember(Value = "GND")]
        #pragma warning disable CS1591
        GND,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEL")]
        #pragma warning disable CS1591
        DEL,
        #pragma warning restore CS1591
        [EnumMember(Value = "ATIS")]
        #pragma warning disable CS1591
        ATIS,
        #pragma warning restore CS1591
    }
}
