// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.V2.Subcenters.All;
using STRIPES.Services.Endpoints.V2.Subcenters.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace STRIPES.Services.Endpoints.V2.Subcenters
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\subcenters
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubcentersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::STRIPES.Services.Endpoints.V2.Subcenters.All.AllRequestBuilder All
        {
            get => new global::STRIPES.Services.Endpoints.V2.Subcenters.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the STRIPES.Services.Endpoints.v2.subcenters.item collection</summary>
        /// <param name="position">Subcenter ID</param>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.V2.Subcenters.Item.SubcentersItemRequestBuilder"/></returns>
        public global::STRIPES.Services.Endpoints.V2.Subcenters.Item.SubcentersItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::STRIPES.Services.Endpoints.V2.Subcenters.Item.SubcentersItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Subcenters.SubcentersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubcentersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/subcenters", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Subcenters.SubcentersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubcentersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/subcenters", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
