// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.V2.ATCPositions;
using STRIPES.Services.Endpoints.V2.Aircrafts;
using STRIPES.Services.Endpoints.V2.AircraftsVariants;
using STRIPES.Services.Endpoints.V2.Airlines;
using STRIPES.Services.Endpoints.V2.Airports;
using STRIPES.Services.Endpoints.V2.Antennas;
using STRIPES.Services.Endpoints.V2.Centers;
using STRIPES.Services.Endpoints.V2.Countries;
using STRIPES.Services.Endpoints.V2.Creators;
using STRIPES.Services.Endpoints.V2.DepartmentTeams;
using STRIPES.Services.Endpoints.V2.Departments;
using STRIPES.Services.Endpoints.V2.Divisions;
using STRIPES.Services.Endpoints.V2.Fras;
using STRIPES.Services.Endpoints.V2.Languages;
using STRIPES.Services.Endpoints.V2.Motds;
using STRIPES.Services.Endpoints.V2.Navaids;
using STRIPES.Services.Endpoints.V2.Notams;
using STRIPES.Services.Endpoints.V2.Permissions;
using STRIPES.Services.Endpoints.V2.Positions;
using STRIPES.Services.Endpoints.V2.Routes;
using STRIPES.Services.Endpoints.V2.Runways;
using STRIPES.Services.Endpoints.V2.Sectors;
using STRIPES.Services.Endpoints.V2.Servers;
using STRIPES.Services.Endpoints.V2.SimulatorVersions;
using STRIPES.Services.Endpoints.V2.Simulators;
using STRIPES.Services.Endpoints.V2.SoftwareFiles;
using STRIPES.Services.Endpoints.V2.Softwares;
using STRIPES.Services.Endpoints.V2.SpecialAreas;
using STRIPES.Services.Endpoints.V2.Squawks;
using STRIPES.Services.Endpoints.V2.StaffPositions;
using STRIPES.Services.Endpoints.V2.Subcenters;
using STRIPES.Services.Endpoints.V2.UserStaffPositions;
using STRIPES.Services.Endpoints.V2.Users;
using STRIPES.Services.Endpoints.V2.VirtualAirlines;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace STRIPES.Services.Endpoints.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The aircrafts property</summary>
        public global::STRIPES.Services.Endpoints.V2.Aircrafts.AircraftsRequestBuilder Aircrafts
        {
            get => new global::STRIPES.Services.Endpoints.V2.Aircrafts.AircraftsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The aircraftsVariants property</summary>
        public global::STRIPES.Services.Endpoints.V2.AircraftsVariants.AircraftsVariantsRequestBuilder AircraftsVariants
        {
            get => new global::STRIPES.Services.Endpoints.V2.AircraftsVariants.AircraftsVariantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The airlines property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airlines.AirlinesRequestBuilder Airlines
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airlines.AirlinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The airports property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.AirportsRequestBuilder Airports
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.AirportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The antennas property</summary>
        public global::STRIPES.Services.Endpoints.V2.Antennas.AntennasRequestBuilder Antennas
        {
            get => new global::STRIPES.Services.Endpoints.V2.Antennas.AntennasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ATCPositions property</summary>
        public global::STRIPES.Services.Endpoints.V2.ATCPositions.ATCPositionsRequestBuilder ATCPositions
        {
            get => new global::STRIPES.Services.Endpoints.V2.ATCPositions.ATCPositionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The centers property</summary>
        public global::STRIPES.Services.Endpoints.V2.Centers.CentersRequestBuilder Centers
        {
            get => new global::STRIPES.Services.Endpoints.V2.Centers.CentersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The countries property</summary>
        public global::STRIPES.Services.Endpoints.V2.Countries.CountriesRequestBuilder Countries
        {
            get => new global::STRIPES.Services.Endpoints.V2.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The creators property</summary>
        public global::STRIPES.Services.Endpoints.V2.Creators.CreatorsRequestBuilder Creators
        {
            get => new global::STRIPES.Services.Endpoints.V2.Creators.CreatorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The departments property</summary>
        public global::STRIPES.Services.Endpoints.V2.Departments.DepartmentsRequestBuilder Departments
        {
            get => new global::STRIPES.Services.Endpoints.V2.Departments.DepartmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The departmentTeams property</summary>
        public global::STRIPES.Services.Endpoints.V2.DepartmentTeams.DepartmentTeamsRequestBuilder DepartmentTeams
        {
            get => new global::STRIPES.Services.Endpoints.V2.DepartmentTeams.DepartmentTeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The divisions property</summary>
        public global::STRIPES.Services.Endpoints.V2.Divisions.DivisionsRequestBuilder Divisions
        {
            get => new global::STRIPES.Services.Endpoints.V2.Divisions.DivisionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fras property</summary>
        public global::STRIPES.Services.Endpoints.V2.Fras.FrasRequestBuilder Fras
        {
            get => new global::STRIPES.Services.Endpoints.V2.Fras.FrasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The languages property</summary>
        public global::STRIPES.Services.Endpoints.V2.Languages.LanguagesRequestBuilder Languages
        {
            get => new global::STRIPES.Services.Endpoints.V2.Languages.LanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The motds property</summary>
        public global::STRIPES.Services.Endpoints.V2.Motds.MotdsRequestBuilder Motds
        {
            get => new global::STRIPES.Services.Endpoints.V2.Motds.MotdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The navaids property</summary>
        public global::STRIPES.Services.Endpoints.V2.Navaids.NavaidsRequestBuilder Navaids
        {
            get => new global::STRIPES.Services.Endpoints.V2.Navaids.NavaidsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notams property</summary>
        public global::STRIPES.Services.Endpoints.V2.Notams.NotamsRequestBuilder Notams
        {
            get => new global::STRIPES.Services.Endpoints.V2.Notams.NotamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::STRIPES.Services.Endpoints.V2.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::STRIPES.Services.Endpoints.V2.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The positions property</summary>
        public global::STRIPES.Services.Endpoints.V2.Positions.PositionsRequestBuilder Positions
        {
            get => new global::STRIPES.Services.Endpoints.V2.Positions.PositionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The routes property</summary>
        public global::STRIPES.Services.Endpoints.V2.Routes.RoutesRequestBuilder Routes
        {
            get => new global::STRIPES.Services.Endpoints.V2.Routes.RoutesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runways property</summary>
        public global::STRIPES.Services.Endpoints.V2.Runways.RunwaysRequestBuilder Runways
        {
            get => new global::STRIPES.Services.Endpoints.V2.Runways.RunwaysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sectors property</summary>
        public global::STRIPES.Services.Endpoints.V2.Sectors.SectorsRequestBuilder Sectors
        {
            get => new global::STRIPES.Services.Endpoints.V2.Sectors.SectorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The servers property</summary>
        public global::STRIPES.Services.Endpoints.V2.Servers.ServersRequestBuilder Servers
        {
            get => new global::STRIPES.Services.Endpoints.V2.Servers.ServersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The simulators property</summary>
        public global::STRIPES.Services.Endpoints.V2.Simulators.SimulatorsRequestBuilder Simulators
        {
            get => new global::STRIPES.Services.Endpoints.V2.Simulators.SimulatorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The simulatorVersions property</summary>
        public global::STRIPES.Services.Endpoints.V2.SimulatorVersions.SimulatorVersionsRequestBuilder SimulatorVersions
        {
            get => new global::STRIPES.Services.Endpoints.V2.SimulatorVersions.SimulatorVersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The softwareFiles property</summary>
        public global::STRIPES.Services.Endpoints.V2.SoftwareFiles.SoftwareFilesRequestBuilder SoftwareFiles
        {
            get => new global::STRIPES.Services.Endpoints.V2.SoftwareFiles.SoftwareFilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The softwares property</summary>
        public global::STRIPES.Services.Endpoints.V2.Softwares.SoftwaresRequestBuilder Softwares
        {
            get => new global::STRIPES.Services.Endpoints.V2.Softwares.SoftwaresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The specialAreas property</summary>
        public global::STRIPES.Services.Endpoints.V2.SpecialAreas.SpecialAreasRequestBuilder SpecialAreas
        {
            get => new global::STRIPES.Services.Endpoints.V2.SpecialAreas.SpecialAreasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The squawks property</summary>
        public global::STRIPES.Services.Endpoints.V2.Squawks.SquawksRequestBuilder Squawks
        {
            get => new global::STRIPES.Services.Endpoints.V2.Squawks.SquawksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The staffPositions property</summary>
        public global::STRIPES.Services.Endpoints.V2.StaffPositions.StaffPositionsRequestBuilder StaffPositions
        {
            get => new global::STRIPES.Services.Endpoints.V2.StaffPositions.StaffPositionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subcenters property</summary>
        public global::STRIPES.Services.Endpoints.V2.Subcenters.SubcentersRequestBuilder Subcenters
        {
            get => new global::STRIPES.Services.Endpoints.V2.Subcenters.SubcentersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::STRIPES.Services.Endpoints.V2.Users.UsersRequestBuilder Users
        {
            get => new global::STRIPES.Services.Endpoints.V2.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userStaffPositions property</summary>
        public global::STRIPES.Services.Endpoints.V2.UserStaffPositions.UserStaffPositionsRequestBuilder UserStaffPositions
        {
            get => new global::STRIPES.Services.Endpoints.V2.UserStaffPositions.UserStaffPositionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The virtualAirlines property</summary>
        public global::STRIPES.Services.Endpoints.V2.VirtualAirlines.VirtualAirlinesRequestBuilder VirtualAirlines
        {
            get => new global::STRIPES.Services.Endpoints.V2.VirtualAirlines.VirtualAirlinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
