// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.V2.Tracker.Connections;
using STRIPES.Services.Endpoints.V2.Tracker.FlightPlans;
using STRIPES.Services.Endpoints.V2.Tracker.Now;
using STRIPES.Services.Endpoints.V2.Tracker.Sessions;
using STRIPES.Services.Endpoints.V2.Tracker.Whazzup;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace STRIPES.Services.Endpoints.V2.Tracker
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\tracker
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrackerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The connections property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.Connections.ConnectionsRequestBuilder Connections
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.Connections.ConnectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The flightPlans property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.FlightPlans.FlightPlansRequestBuilder FlightPlans
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.FlightPlans.FlightPlansRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The now property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.Now.NowRequestBuilder Now
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.Now.NowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sessions property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The whazzup property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.Whazzup.WhazzupRequestBuilder Whazzup
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.Whazzup.WhazzupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Tracker.TrackerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrackerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/tracker", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Tracker.TrackerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrackerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/tracker", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
