// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.V2.Users.Item.Sessions.Now;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace STRIPES.Services.Endpoints.V2.Users.Item.Sessions
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\users\{vid}\sessions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SessionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The now property</summary>
        public global::STRIPES.Services.Endpoints.V2.Users.Item.Sessions.Now.NowRequestBuilder Now
        {
            get => new global::STRIPES.Services.Endpoints.V2.Users.Item.Sessions.Now.NowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Users.Item.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users/{vid}/sessions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Users.Item.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users/{vid}/sessions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
