// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.V2.Notams.All;
using STRIPES.Services.Endpoints.V2.Notams.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace STRIPES.Services.Endpoints.V2.Notams
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\notams
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotamsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::STRIPES.Services.Endpoints.V2.Notams.All.AllRequestBuilder All
        {
            get => new global::STRIPES.Services.Endpoints.V2.Notams.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the STRIPES.Services.Endpoints.v2.notams.item collection</summary>
        /// <param name="position">NOTAM ID</param>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.V2.Notams.Item.NotamsItemRequestBuilder"/></returns>
        public global::STRIPES.Services.Endpoints.V2.Notams.Item.NotamsItemRequestBuilder this[double position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::STRIPES.Services.Endpoints.V2.Notams.Item.NotamsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the STRIPES.Services.Endpoints.v2.notams.item collection</summary>
        /// <param name="position">NOTAM ID</param>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.V2.Notams.Item.NotamsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::STRIPES.Services.Endpoints.V2.Notams.Item.NotamsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::STRIPES.Services.Endpoints.V2.Notams.Item.NotamsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Notams.NotamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotamsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/notams", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Notams.NotamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotamsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/notams", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
