// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.V2.Tracker.Now.Atc;
using STRIPES.Services.Endpoints.V2.Tracker.Now.Connections;
using STRIPES.Services.Endpoints.V2.Tracker.Now.Observers;
using STRIPES.Services.Endpoints.V2.Tracker.Now.Pilots;
using STRIPES.Services.Endpoints.V2.Tracker.Now.Supervisors;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace STRIPES.Services.Endpoints.V2.Tracker.Now
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\tracker\now
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NowRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The atc property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.Now.Atc.AtcRequestBuilder Atc
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.Now.Atc.AtcRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The connections property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.Now.Connections.ConnectionsRequestBuilder Connections
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.Now.Connections.ConnectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The observers property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.Now.Observers.ObserversRequestBuilder Observers
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.Now.Observers.ObserversRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pilots property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.Now.Pilots.PilotsRequestBuilder Pilots
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.Now.Pilots.PilotsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The supervisors property</summary>
        public global::STRIPES.Services.Endpoints.V2.Tracker.Now.Supervisors.SupervisorsRequestBuilder Supervisors
        {
            get => new global::STRIPES.Services.Endpoints.V2.Tracker.Now.Supervisors.SupervisorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Tracker.Now.NowRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NowRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/tracker/now", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Tracker.Now.NowRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NowRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/tracker/now", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
