// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.Models;
using STRIPES.Services.Endpoints.V2.Airports.Item.ATCPositions;
using STRIPES.Services.Endpoints.V2.Airports.Item.Atis;
using STRIPES.Services.Endpoints.V2.Airports.Item.Metar;
using STRIPES.Services.Endpoints.V2.Airports.Item.Notams;
using STRIPES.Services.Endpoints.V2.Airports.Item.Runways;
using STRIPES.Services.Endpoints.V2.Airports.Item.ShortTaf;
using STRIPES.Services.Endpoints.V2.Airports.Item.Squawks;
using STRIPES.Services.Endpoints.V2.Airports.Item.Stats;
using STRIPES.Services.Endpoints.V2.Airports.Item.Taf;
using STRIPES.Services.Endpoints.V2.Airports.Item.Traffics;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace STRIPES.Services.Endpoints.V2.Airports.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\airports\{airport-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AirportItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ATCPositions property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.ATCPositions.ATCPositionsRequestBuilder ATCPositions
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.ATCPositions.ATCPositionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The atis property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.Atis.AtisRequestBuilder Atis
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.Atis.AtisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metar property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.Metar.MetarRequestBuilder Metar
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.Metar.MetarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notams property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.Notams.NotamsRequestBuilder Notams
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.Notams.NotamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runways property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.Runways.RunwaysRequestBuilder Runways
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.Runways.RunwaysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shortTaf property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.ShortTaf.ShortTafRequestBuilder ShortTaf
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.ShortTaf.ShortTafRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The squawks property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.Squawks.SquawksRequestBuilder Squawks
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.Squawks.SquawksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stats property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.Stats.StatsRequestBuilder Stats
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The taf property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.Taf.TafRequestBuilder Taf
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.Taf.TafRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The traffics property</summary>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.Traffics.TrafficsRequestBuilder Traffics
        {
            get => new global::STRIPES.Services.Endpoints.V2.Airports.Item.Traffics.TrafficsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Airports.Item.AirportItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AirportItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/airports/{airport%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Airports.Item.AirportItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AirportItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/airports/{airport%2Did}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.AirportDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::STRIPES.Services.Endpoints.Models.SwaggerResponsesDto">When receiving a 401 status code</exception>
        /// <exception cref="global::STRIPES.Services.Endpoints.Models.SwaggerResponsesDto">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::STRIPES.Services.Endpoints.Models.AirportDto?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::STRIPES.Services.Endpoints.Models.AirportDto> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::STRIPES.Services.Endpoints.Models.SwaggerResponsesDto.CreateFromDiscriminatorValue },
                { "404", global::STRIPES.Services.Endpoints.Models.SwaggerResponsesDto.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::STRIPES.Services.Endpoints.Models.AirportDto>(requestInfo, global::STRIPES.Services.Endpoints.Models.AirportDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.V2.Airports.Item.AirportItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::STRIPES.Services.Endpoints.V2.Airports.Item.AirportItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::STRIPES.Services.Endpoints.V2.Airports.Item.AirportItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AirportItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
