// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.V2.Users.Item;
using STRIPES.Services.Endpoints.V2.Users.Me;
using STRIPES.Services.Endpoints.V2.Users.Staff;
using STRIPES.Services.Endpoints.V2.Users.Staffs;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace STRIPES.Services.Endpoints.V2.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The me property</summary>
        public global::STRIPES.Services.Endpoints.V2.Users.Me.MeRequestBuilder Me
        {
            get => new global::STRIPES.Services.Endpoints.V2.Users.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The staff property</summary>
        public global::STRIPES.Services.Endpoints.V2.Users.Staff.StaffRequestBuilder Staff
        {
            get => new global::STRIPES.Services.Endpoints.V2.Users.Staff.StaffRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The staffs property</summary>
        public global::STRIPES.Services.Endpoints.V2.Users.Staffs.StaffsRequestBuilder Staffs
        {
            get => new global::STRIPES.Services.Endpoints.V2.Users.Staffs.StaffsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the STRIPES.Services.Endpoints.v2.users.item collection</summary>
        /// <param name="position">User&apos;s VID (use &apos;me&apos; for current logged in user)</param>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.V2.Users.Item.WithVItemRequestBuilder"/></returns>
        public global::STRIPES.Services.Endpoints.V2.Users.Item.WithVItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("vid", position);
                return new global::STRIPES.Services.Endpoints.V2.Users.Item.WithVItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
