// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AircraftRequestDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aircraftId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AircraftId { get; set; }
#nullable restore
#else
        public string AircraftId { get; set; }
#endif
        /// <summary>The equipments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Equipments { get; set; }
#nullable restore
#else
        public List<string> Equipments { get; set; }
#endif
        /// <summary>The registration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Registration { get; set; }
#nullable restore
#else
        public string Registration { get; set; }
#endif
        /// <summary>The remarks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remarks { get; set; }
#nullable restore
#else
        public string Remarks { get; set; }
#endif
        /// <summary>The selcal property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Selcal { get; set; }
#nullable restore
#else
        public string Selcal { get; set; }
#endif
        /// <summary>The transponderTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TransponderTypes { get; set; }
#nullable restore
#else
        public List<string> TransponderTypes { get; set; }
#endif
        /// <summary>The wakeTurbulence property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WakeTurbulence { get; set; }
#nullable restore
#else
        public string WakeTurbulence { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.Models.AircraftRequestDto"/> and sets the default values.
        /// </summary>
        public AircraftRequestDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.AircraftRequestDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::STRIPES.Services.Endpoints.Models.AircraftRequestDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::STRIPES.Services.Endpoints.Models.AircraftRequestDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aircraftId", n => { AircraftId = n.GetStringValue(); } },
                { "equipments", n => { Equipments = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "registration", n => { Registration = n.GetStringValue(); } },
                { "remarks", n => { Remarks = n.GetStringValue(); } },
                { "selcal", n => { Selcal = n.GetStringValue(); } },
                { "transponderTypes", n => { TransponderTypes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "wakeTurbulence", n => { WakeTurbulence = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("aircraftId", AircraftId);
            writer.WriteCollectionOfPrimitiveValues<string>("equipments", Equipments);
            writer.WriteStringValue("registration", Registration);
            writer.WriteStringValue("remarks", Remarks);
            writer.WriteStringValue("selcal", Selcal);
            writer.WriteCollectionOfPrimitiveValues<string>("transponderTypes", TransponderTypes);
            writer.WriteStringValue("wakeTurbulence", WakeTurbulence);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
