// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AirportTrafficsDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The flightover property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.AirportTrafficDto? Flightover { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.AirportTrafficDto Flightover { get; set; }
#endif
        /// <summary>The inbound property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.AirportTrafficDto? Inbound { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.AirportTrafficDto Inbound { get; set; }
#endif
        /// <summary>The outbound property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.AirportTrafficDto? Outbound { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.AirportTrafficDto Outbound { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.Models.AirportTrafficsDto"/> and sets the default values.
        /// </summary>
        public AirportTrafficsDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.AirportTrafficsDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::STRIPES.Services.Endpoints.Models.AirportTrafficsDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::STRIPES.Services.Endpoints.Models.AirportTrafficsDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "flightover", n => { Flightover = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.AirportTrafficDto>(global::STRIPES.Services.Endpoints.Models.AirportTrafficDto.CreateFromDiscriminatorValue); } },
                { "inbound", n => { Inbound = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.AirportTrafficDto>(global::STRIPES.Services.Endpoints.Models.AirportTrafficDto.CreateFromDiscriminatorValue); } },
                { "outbound", n => { Outbound = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.AirportTrafficDto>(global::STRIPES.Services.Endpoints.Models.AirportTrafficDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.AirportTrafficDto>("flightover", Flightover);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.AirportTrafficDto>("inbound", Inbound);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.AirportTrafficDto>("outbound", Outbound);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
