// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BaseFlightPlanDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Time in seconds</summary>
        public double? ActualDepartureTime { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aircraftId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AircraftId { get; set; }
#nullable restore
#else
        public string AircraftId { get; set; }
#endif
        /// <summary>The aircraftNumber property</summary>
        public double? AircraftNumber { get; set; }
        /// <summary>The alternative2Id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alternative2Id { get; set; }
#nullable restore
#else
        public string Alternative2Id { get; set; }
#endif
        /// <summary>The alternativeId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternativeId { get; set; }
#nullable restore
#else
        public string AlternativeId { get; set; }
#endif
        /// <summary>The arrivalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArrivalId { get; set; }
#nullable restore
#else
        public string ArrivalId { get; set; }
#endif
        /// <summary>The departureId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DepartureId { get; set; }
#nullable restore
#else
        public string DepartureId { get; set; }
#endif
        /// <summary>Time in seconds</summary>
        public double? DepartureTime { get; set; }
        /// <summary>Time in seconds</summary>
        public double? Eet { get; set; }
        /// <summary>Time in seconds</summary>
        public double? Endurance { get; set; }
        /// <summary>The flightRules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FlightRules { get; set; }
#nullable restore
#else
        public string FlightRules { get; set; }
#endif
        /// <summary>The flightType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FlightType { get; set; }
#nullable restore
#else
        public string FlightType { get; set; }
#endif
        /// <summary>The id property</summary>
        public double? Id { get; set; }
        /// <summary>The level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level { get; set; }
#nullable restore
#else
        public string Level { get; set; }
#endif
        /// <summary>The peopleOnBoard property</summary>
        public double? PeopleOnBoard { get; set; }
        /// <summary>The remarks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remarks { get; set; }
#nullable restore
#else
        public string Remarks { get; set; }
#endif
        /// <summary>The revision property</summary>
        public double? Revision { get; set; }
        /// <summary>The route property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Route { get; set; }
#nullable restore
#else
        public string Route { get; set; }
#endif
        /// <summary>The sessionId property</summary>
        public double? SessionId { get; set; }
        /// <summary>The speed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Speed { get; set; }
#nullable restore
#else
        public string Speed { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.Models.BaseFlightPlanDto"/> and sets the default values.
        /// </summary>
        public BaseFlightPlanDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.BaseFlightPlanDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::STRIPES.Services.Endpoints.Models.BaseFlightPlanDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::STRIPES.Services.Endpoints.Models.BaseFlightPlanDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actualDepartureTime", n => { ActualDepartureTime = n.GetDoubleValue(); } },
                { "aircraftId", n => { AircraftId = n.GetStringValue(); } },
                { "aircraftNumber", n => { AircraftNumber = n.GetDoubleValue(); } },
                { "alternative2Id", n => { Alternative2Id = n.GetStringValue(); } },
                { "alternativeId", n => { AlternativeId = n.GetStringValue(); } },
                { "arrivalId", n => { ArrivalId = n.GetStringValue(); } },
                { "departureId", n => { DepartureId = n.GetStringValue(); } },
                { "departureTime", n => { DepartureTime = n.GetDoubleValue(); } },
                { "eet", n => { Eet = n.GetDoubleValue(); } },
                { "endurance", n => { Endurance = n.GetDoubleValue(); } },
                { "flightRules", n => { FlightRules = n.GetStringValue(); } },
                { "flightType", n => { FlightType = n.GetStringValue(); } },
                { "id", n => { Id = n.GetDoubleValue(); } },
                { "level", n => { Level = n.GetStringValue(); } },
                { "peopleOnBoard", n => { PeopleOnBoard = n.GetDoubleValue(); } },
                { "remarks", n => { Remarks = n.GetStringValue(); } },
                { "revision", n => { Revision = n.GetDoubleValue(); } },
                { "route", n => { Route = n.GetStringValue(); } },
                { "sessionId", n => { SessionId = n.GetDoubleValue(); } },
                { "speed", n => { Speed = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("actualDepartureTime", ActualDepartureTime);
            writer.WriteStringValue("aircraftId", AircraftId);
            writer.WriteDoubleValue("aircraftNumber", AircraftNumber);
            writer.WriteStringValue("alternative2Id", Alternative2Id);
            writer.WriteStringValue("alternativeId", AlternativeId);
            writer.WriteStringValue("arrivalId", ArrivalId);
            writer.WriteStringValue("departureId", DepartureId);
            writer.WriteDoubleValue("departureTime", DepartureTime);
            writer.WriteDoubleValue("eet", Eet);
            writer.WriteDoubleValue("endurance", Endurance);
            writer.WriteStringValue("flightRules", FlightRules);
            writer.WriteStringValue("flightType", FlightType);
            writer.WriteDoubleValue("id", Id);
            writer.WriteStringValue("level", Level);
            writer.WriteDoubleValue("peopleOnBoard", PeopleOnBoard);
            writer.WriteStringValue("remarks", Remarks);
            writer.WriteDoubleValue("revision", Revision);
            writer.WriteStringValue("route", Route);
            writer.WriteDoubleValue("sessionId", SessionId);
            writer.WriteStringValue("speed", Speed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
