// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BaseUserRatingDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The atcRating property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.BaseRatingDto? AtcRating { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.BaseRatingDto AtcRating { get; set; }
#endif
        /// <summary>The isAtc property</summary>
        public bool? IsAtc { get; set; }
        /// <summary>The isPilot property</summary>
        public bool? IsPilot { get; set; }
        /// <summary>The networkRating property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.NetworkRatingDto? NetworkRating { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.NetworkRatingDto NetworkRating { get; set; }
#endif
        /// <summary>The pilotRating property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.BaseRatingDto? PilotRating { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.BaseRatingDto PilotRating { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.Models.BaseUserRatingDto"/> and sets the default values.
        /// </summary>
        public BaseUserRatingDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.BaseUserRatingDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::STRIPES.Services.Endpoints.Models.BaseUserRatingDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::STRIPES.Services.Endpoints.Models.BaseUserRatingDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "atcRating", n => { AtcRating = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.BaseRatingDto>(global::STRIPES.Services.Endpoints.Models.BaseRatingDto.CreateFromDiscriminatorValue); } },
                { "isAtc", n => { IsAtc = n.GetBoolValue(); } },
                { "isPilot", n => { IsPilot = n.GetBoolValue(); } },
                { "networkRating", n => { NetworkRating = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.NetworkRatingDto>(global::STRIPES.Services.Endpoints.Models.NetworkRatingDto.CreateFromDiscriminatorValue); } },
                { "pilotRating", n => { PilotRating = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.BaseRatingDto>(global::STRIPES.Services.Endpoints.Models.BaseRatingDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.BaseRatingDto>("atcRating", AtcRating);
            writer.WriteBoolValue("isAtc", IsAtc);
            writer.WriteBoolValue("isPilot", IsPilot);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.NetworkRatingDto>("networkRating", NetworkRating);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.BaseRatingDto>("pilotRating", PilotRating);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
