// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateFlightPlanDto_altitudeType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "F")]
        #pragma warning disable CS1591
        F,
        #pragma warning restore CS1591
        [EnumMember(Value = "A")]
        #pragma warning disable CS1591
        A,
        #pragma warning restore CS1591
        [EnumMember(Value = "S")]
        #pragma warning disable CS1591
        S,
        #pragma warning restore CS1591
        [EnumMember(Value = "M")]
        #pragma warning disable CS1591
        M,
        #pragma warning restore CS1591
        [EnumMember(Value = "VFR")]
        #pragma warning disable CS1591
        VFR,
        #pragma warning restore CS1591
    }
}
