// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateFlightPlanDto_aircraftWakeTurbulence
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "L")]
        #pragma warning disable CS1591
        L,
        #pragma warning restore CS1591
        [EnumMember(Value = "M")]
        #pragma warning disable CS1591
        M,
        #pragma warning restore CS1591
        [EnumMember(Value = "H")]
        #pragma warning disable CS1591
        H,
        #pragma warning restore CS1591
        [EnumMember(Value = "J")]
        #pragma warning disable CS1591
        J,
        #pragma warning restore CS1591
    }
}
