// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateFlightPlanDto_cruisingSpeedType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "N")]
        #pragma warning disable CS1591
        N,
        #pragma warning restore CS1591
        [EnumMember(Value = "M")]
        #pragma warning disable CS1591
        M,
        #pragma warning restore CS1591
        [EnumMember(Value = "K")]
        #pragma warning disable CS1591
        K,
        #pragma warning restore CS1591
    }
}
