// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlightPlanSummaryDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aircraft property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.AircraftSummaryDto? Aircraft { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.AircraftSummaryDto Aircraft { get; set; }
#endif
        /// <summary>The aircraftId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AircraftId { get; set; }
#nullable restore
#else
        public string AircraftId { get; set; }
#endif
        /// <summary>The alternative property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.BaseAirportDto? Alternative { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.BaseAirportDto Alternative { get; set; }
#endif
        /// <summary>The alternative2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.BaseAirportDto? Alternative2 { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.BaseAirportDto Alternative2 { get; set; }
#endif
        /// <summary>The arrival property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.BaseAirportDto? Arrival { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.BaseAirportDto Arrival { get; set; }
#endif
        /// <summary>The arrivalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArrivalId { get; set; }
#nullable restore
#else
        public string ArrivalId { get; set; }
#endif
        /// <summary>The departure property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.BaseAirportDto? Departure { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.BaseAirportDto Departure { get; set; }
#endif
        /// <summary>The departureId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DepartureId { get; set; }
#nullable restore
#else
        public string DepartureId { get; set; }
#endif
        /// <summary>The id property</summary>
        public double? Id { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.Models.FlightPlanSummaryDto"/> and sets the default values.
        /// </summary>
        public FlightPlanSummaryDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.FlightPlanSummaryDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::STRIPES.Services.Endpoints.Models.FlightPlanSummaryDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::STRIPES.Services.Endpoints.Models.FlightPlanSummaryDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aircraft", n => { Aircraft = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.AircraftSummaryDto>(global::STRIPES.Services.Endpoints.Models.AircraftSummaryDto.CreateFromDiscriminatorValue); } },
                { "aircraftId", n => { AircraftId = n.GetStringValue(); } },
                { "alternative", n => { Alternative = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.BaseAirportDto>(global::STRIPES.Services.Endpoints.Models.BaseAirportDto.CreateFromDiscriminatorValue); } },
                { "alternative2", n => { Alternative2 = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.BaseAirportDto>(global::STRIPES.Services.Endpoints.Models.BaseAirportDto.CreateFromDiscriminatorValue); } },
                { "arrival", n => { Arrival = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.BaseAirportDto>(global::STRIPES.Services.Endpoints.Models.BaseAirportDto.CreateFromDiscriminatorValue); } },
                { "arrivalId", n => { ArrivalId = n.GetStringValue(); } },
                { "departure", n => { Departure = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.BaseAirportDto>(global::STRIPES.Services.Endpoints.Models.BaseAirportDto.CreateFromDiscriminatorValue); } },
                { "departureId", n => { DepartureId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.AircraftSummaryDto>("aircraft", Aircraft);
            writer.WriteStringValue("aircraftId", AircraftId);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.BaseAirportDto>("alternative", Alternative);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.BaseAirportDto>("alternative2", Alternative2);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.BaseAirportDto>("arrival", Arrival);
            writer.WriteStringValue("arrivalId", ArrivalId);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.BaseAirportDto>("departure", Departure);
            writer.WriteStringValue("departureId", DepartureId);
            writer.WriteDoubleValue("id", Id);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
