// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FraDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The atcPositionId property</summary>
        public double? AtcPositionId { get; set; }
        /// <summary>The date property</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>The dayFri property</summary>
        public bool? DayFri { get; set; }
        /// <summary>The dayMon property</summary>
        public bool? DayMon { get; set; }
        /// <summary>The daySat property</summary>
        public bool? DaySat { get; set; }
        /// <summary>The daySun property</summary>
        public bool? DaySun { get; set; }
        /// <summary>The dayThu property</summary>
        public bool? DayThu { get; set; }
        /// <summary>The dayTue property</summary>
        public bool? DayTue { get; set; }
        /// <summary>The dayWed property</summary>
        public bool? DayWed { get; set; }
        /// <summary>The endTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndTime { get; set; }
#nullable restore
#else
        public string EndTime { get; set; }
#endif
        /// <summary>The id property</summary>
        public double? Id { get; set; }
        /// <summary>The minAtc property</summary>
        public double? MinAtc { get; set; }
        /// <summary>The startTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartTime { get; set; }
#nullable restore
#else
        public string StartTime { get; set; }
#endif
        /// <summary>The subcenterId property</summary>
        public double? SubcenterId { get; set; }
        /// <summary>The userId property</summary>
        public double? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.Models.FraDto"/> and sets the default values.
        /// </summary>
        public FraDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.FraDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::STRIPES.Services.Endpoints.Models.FraDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::STRIPES.Services.Endpoints.Models.FraDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "atcPositionId", n => { AtcPositionId = n.GetDoubleValue(); } },
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "dayFri", n => { DayFri = n.GetBoolValue(); } },
                { "dayMon", n => { DayMon = n.GetBoolValue(); } },
                { "daySat", n => { DaySat = n.GetBoolValue(); } },
                { "daySun", n => { DaySun = n.GetBoolValue(); } },
                { "dayThu", n => { DayThu = n.GetBoolValue(); } },
                { "dayTue", n => { DayTue = n.GetBoolValue(); } },
                { "dayWed", n => { DayWed = n.GetBoolValue(); } },
                { "endTime", n => { EndTime = n.GetStringValue(); } },
                { "id", n => { Id = n.GetDoubleValue(); } },
                { "minAtc", n => { MinAtc = n.GetDoubleValue(); } },
                { "startTime", n => { StartTime = n.GetStringValue(); } },
                { "subcenterId", n => { SubcenterId = n.GetDoubleValue(); } },
                { "userId", n => { UserId = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteDoubleValue("atcPositionId", AtcPositionId);
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteBoolValue("dayFri", DayFri);
            writer.WriteBoolValue("dayMon", DayMon);
            writer.WriteBoolValue("daySat", DaySat);
            writer.WriteBoolValue("daySun", DaySun);
            writer.WriteBoolValue("dayThu", DayThu);
            writer.WriteBoolValue("dayTue", DayTue);
            writer.WriteBoolValue("dayWed", DayWed);
            writer.WriteStringValue("endTime", EndTime);
            writer.WriteDoubleValue("id", Id);
            writer.WriteDoubleValue("minAtc", MinAtc);
            writer.WriteStringValue("startTime", StartTime);
            writer.WriteDoubleValue("subcenterId", SubcenterId);
            writer.WriteDoubleValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
