// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NowAtcSummaryDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The atcPosition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.ATCPositionDto? AtcPosition { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.ATCPositionDto AtcPosition { get; set; }
#endif
        /// <summary>The atcSession property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.AtcSessionDto? AtcSession { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.AtcSessionDto AtcSession { get; set; }
#endif
        /// <summary>The callsign property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Callsign { get; set; }
#nullable restore
#else
        public string Callsign { get; set; }
#endif
        /// <summary>The connectionType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionType { get; set; }
#nullable restore
#else
        public string ConnectionType { get; set; }
#endif
        /// <summary>The id property</summary>
        public double? Id { get; set; }
        /// <summary>The subcenter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.SubcenterDto? Subcenter { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.SubcenterDto Subcenter { get; set; }
#endif
        /// <summary>The userId property</summary>
        public double? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.Models.NowAtcSummaryDto"/> and sets the default values.
        /// </summary>
        public NowAtcSummaryDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.NowAtcSummaryDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::STRIPES.Services.Endpoints.Models.NowAtcSummaryDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::STRIPES.Services.Endpoints.Models.NowAtcSummaryDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "atcPosition", n => { AtcPosition = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.ATCPositionDto>(global::STRIPES.Services.Endpoints.Models.ATCPositionDto.CreateFromDiscriminatorValue); } },
                { "atcSession", n => { AtcSession = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.AtcSessionDto>(global::STRIPES.Services.Endpoints.Models.AtcSessionDto.CreateFromDiscriminatorValue); } },
                { "callsign", n => { Callsign = n.GetStringValue(); } },
                { "connectionType", n => { ConnectionType = n.GetStringValue(); } },
                { "id", n => { Id = n.GetDoubleValue(); } },
                { "subcenter", n => { Subcenter = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.SubcenterDto>(global::STRIPES.Services.Endpoints.Models.SubcenterDto.CreateFromDiscriminatorValue); } },
                { "userId", n => { UserId = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.ATCPositionDto>("atcPosition", AtcPosition);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.AtcSessionDto>("atcSession", AtcSession);
            writer.WriteStringValue("callsign", Callsign);
            writer.WriteStringValue("connectionType", ConnectionType);
            writer.WriteDoubleValue("id", Id);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.SubcenterDto>("subcenter", Subcenter);
            writer.WriteDoubleValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
