// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NowSupervisorsDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The callsign property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Callsign { get; set; }
#nullable restore
#else
        public string Callsign { get; set; }
#endif
        /// <summary>The connectionType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionType { get; set; }
#nullable restore
#else
        public string ConnectionType { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The hideSupervisor property</summary>
        public bool? HideSupervisor { get; set; }
        /// <summary>The id property</summary>
        public double? Id { get; set; }
        /// <summary>The serverId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerId { get; set; }
#nullable restore
#else
        public string ServerId { get; set; }
#endif
        /// <summary>The time property</summary>
        public double? Time { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::STRIPES.Services.Endpoints.Models.UserSummaryBaseDto? User { get; set; }
#nullable restore
#else
        public global::STRIPES.Services.Endpoints.Models.UserSummaryBaseDto User { get; set; }
#endif
        /// <summary>The userId property</summary>
        public double? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.Models.NowSupervisorsDto"/> and sets the default values.
        /// </summary>
        public NowSupervisorsDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.NowSupervisorsDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::STRIPES.Services.Endpoints.Models.NowSupervisorsDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::STRIPES.Services.Endpoints.Models.NowSupervisorsDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "callsign", n => { Callsign = n.GetStringValue(); } },
                { "connectionType", n => { ConnectionType = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "hideSupervisor", n => { HideSupervisor = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetDoubleValue(); } },
                { "serverId", n => { ServerId = n.GetStringValue(); } },
                { "time", n => { Time = n.GetDoubleValue(); } },
                { "user", n => { User = n.GetObjectValue<global::STRIPES.Services.Endpoints.Models.UserSummaryBaseDto>(global::STRIPES.Services.Endpoints.Models.UserSummaryBaseDto.CreateFromDiscriminatorValue); } },
                { "userId", n => { UserId = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("callsign", Callsign);
            writer.WriteStringValue("connectionType", ConnectionType);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteBoolValue("hideSupervisor", HideSupervisor);
            writer.WriteDoubleValue("id", Id);
            writer.WriteStringValue("serverId", ServerId);
            writer.WriteDoubleValue("time", Time);
            writer.WriteObjectValue<global::STRIPES.Services.Endpoints.Models.UserSummaryBaseDto>("user", User);
            writer.WriteDoubleValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
