// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaginatedDepartmentResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::STRIPES.Services.Endpoints.Models.DepartmentResponseDto>? Items { get; set; }
#nullable restore
#else
        public List<global::STRIPES.Services.Endpoints.Models.DepartmentResponseDto> Items { get; set; }
#endif
        /// <summary>The page property</summary>
        public double? Page { get; set; }
        /// <summary>The pages property</summary>
        public double? Pages { get; set; }
        /// <summary>The perPage property</summary>
        public double? PerPage { get; set; }
        /// <summary>The totalItems property</summary>
        public double? TotalItems { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.Models.PaginatedDepartmentResponseDto"/> and sets the default values.
        /// </summary>
        public PaginatedDepartmentResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.Models.PaginatedDepartmentResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::STRIPES.Services.Endpoints.Models.PaginatedDepartmentResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::STRIPES.Services.Endpoints.Models.PaginatedDepartmentResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::STRIPES.Services.Endpoints.Models.DepartmentResponseDto>(global::STRIPES.Services.Endpoints.Models.DepartmentResponseDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "page", n => { Page = n.GetDoubleValue(); } },
                { "pages", n => { Pages = n.GetDoubleValue(); } },
                { "perPage", n => { PerPage = n.GetDoubleValue(); } },
                { "totalItems", n => { TotalItems = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::STRIPES.Services.Endpoints.Models.DepartmentResponseDto>("items", Items);
            writer.WriteDoubleValue("page", Page);
            writer.WriteDoubleValue("pages", Pages);
            writer.WriteDoubleValue("perPage", PerPage);
            writer.WriteDoubleValue("totalItems", TotalItems);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
