// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace STRIPES.Services.Endpoints.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserHoursDto_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "pilot")]
        #pragma warning disable CS1591
        Pilot,
        #pragma warning restore CS1591
        [EnumMember(Value = "atc")]
        #pragma warning disable CS1591
        Atc,
        #pragma warning restore CS1591
        [EnumMember(Value = "staff")]
        #pragma warning disable CS1591
        Staff,
        #pragma warning restore CS1591
    }
}
