// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.V2.Navaids.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace STRIPES.Services.Endpoints.V2.Navaids
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\navaids
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NavaidsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the STRIPES.Services.Endpoints.v2.navaids.item collection</summary>
        /// <param name="position">Navaid type</param>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.V2.Navaids.Item.WithTypeItemRequestBuilder"/></returns>
        public global::STRIPES.Services.Endpoints.V2.Navaids.Item.WithTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("type", position);
                return new global::STRIPES.Services.Endpoints.V2.Navaids.Item.WithTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Navaids.NavaidsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NavaidsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/navaids", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Navaids.NavaidsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NavaidsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/navaids", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
