// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using STRIPES.Services.Endpoints.V2.Fras.Check.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace STRIPES.Services.Endpoints.V2.Fras.Check.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\fras\check\{callsign}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCallsignItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the STRIPES.Services.Endpoints.v2.fras.check.item.item collection</summary>
        /// <param name="position">User&apos;s VID</param>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.V2.Fras.Check.Item.Item.WithVItemRequestBuilder"/></returns>
        public global::STRIPES.Services.Endpoints.V2.Fras.Check.Item.Item.WithVItemRequestBuilder this[double position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("vid", position);
                return new global::STRIPES.Services.Endpoints.V2.Fras.Check.Item.Item.WithVItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the STRIPES.Services.Endpoints.v2.fras.check.item.item collection</summary>
        /// <param name="position">User&apos;s VID</param>
        /// <returns>A <see cref="global::STRIPES.Services.Endpoints.V2.Fras.Check.Item.Item.WithVItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::STRIPES.Services.Endpoints.V2.Fras.Check.Item.Item.WithVItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("vid", position);
                return new global::STRIPES.Services.Endpoints.V2.Fras.Check.Item.Item.WithVItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Fras.Check.Item.WithCallsignItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCallsignItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/fras/check/{callsign}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::STRIPES.Services.Endpoints.V2.Fras.Check.Item.WithCallsignItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCallsignItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/fras/check/{callsign}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
